In [ ]:
aList = ["John", 22/7, "Toronto", True]
print(aList)

['Mamang', 3.142857142857143, 'Cecep', True]


In [ ]:
Mahasiswa = ["Ryan Chandra", 2021071007, "Informatika","Desain Analisis dan Algoritma", "19/09/2022", "Universitas Pembangunan Jaya"]
print(Mahasiswa)

['Ryan Chandra', 2021071007, 'Informatika', 'Desain Analisis dan Algoritma', '19/09/2022', 'Universitas Pembangunan Jaya']


In [ ]:
bin_colors = ["Red", "Green", "Blue", "Yellow"]
bin_colors[2]

'Blue'

In [ ]:
Mahasiswa[1]

2021071007

In [ ]:
Mahasiswa[5]

'Universitas Pembangunan Jaya'

In [ ]:
bin_colors[2:4]

['Blue', 'Yellow']

In [ ]:
Mahasiswa[1:3]

[2021071007, 'Informatika']

In [ ]:
for Warna in bin_colors:
 print(Warna + " Square")

Red Square
Green Square
Blue Square
Yellow Square


In [ ]:
for i in Mahasiswa:
  print("UPJ", i)

UPJ Ryan Chandra
UPJ 2021071007
UPJ Informatika
UPJ Desain Analisis dan Algoritma
UPJ 19/09/2022
UPJ Universitas Pembangunan Jaya


In [ ]:
bin_colors = ('RED', 'GREEN', 'BLUE', 'YELLOW')
bin_colors[1]

'GREEN'

In [ ]:
bin_colors[2:]

('BLUE', 'YELLOW')

In [ ]:
UPJ = ('Universitas','Pembangunan','Jaya')
print(UPJ)

('Universitas', 'Pembangunan', 'Jaya')


In [ ]:
N1 = (100,(200,400,600),(300),(400,800))
print("Pertama = ", N1[0])
print("Kedua   = ", N1[1])
print("Ketiga  = ", N1[2])
print("Keempat = ", N1[3])

Pertama =  100
Kedua   =  (200, 400, 600)
Ketiga  =  300
Keempat =  (400, 800)


In [ ]:
bin_colors = {
"manual_colors" : "Yellow", 
"approved_color": "Green",
"refused_color" : "Red"
}
print(bin_colors)

{'manual_colors': 'Yellow', 'approved_color': 'Green', 'refused_color': 'Red'}


In [ ]:
bin_colors.get('approved_color')

'Green'

In [ ]:
bin_colors['approved_color']

'Green'

In [ ]:
bin_colors['approved_color'] = "Purple"
print(bin_colors)

{'manual_colors': 'Yellow', 'approved_color': 'Purple', 'refused_color': 'Red', 'manual_color': 'Pink', ('approved_color', 'manual_color'): 'Purple'}


In [ ]:
Latihan = {
"Nama"        : "Ryan Chandra", 
"NIM"         : "2021071007",
"Prodi"       : "Informatika",
"Universitas" : "UPJ"
}
print(Latihan)

{'Nama': 'Ryan Chandra', 'NIM': '2021071007', 'Prodi': 'Informatika', 'Universitas': 'UPJ'}


In [ ]:
green = {'rumput', 'hijau'}
print(green)

{'hijau', 'rumput'}


In [ ]:
green = {'rumput', 'hijau', 'hijau'}
print(green)

{'hijau', 'rumput'}


In [ ]:
yellow = {'dandelions', 'leaves', 'fire hydrant'}
red = {'leaves', 'fire hydrant', 'rose', 'blood'}
print(yellow&red)

{'fire hydrant', 'leaves'}


In [ ]:
import pandas as pd
df = pd.DataFrame([
    ['1', 'Fares', 32, True],
    ['2', 'Elena', 23, False],
    ['3',' steven', 40, True]])

In [ ]:
df.columns = ['id','name','age','decision']
df 

id     name  age  decision
0  1    Fares   32      True
1  2    Elena   23     False
2  3   steven   40      True

In [ ]:
import numpy as np
myMatrix = np.array([[11,12,13],[21,22,23],[31,32,33]])
print(myMatrix)

[[11 12 13]
 [21 22 23]
 [31 32 33]]


In [ ]:
print(type(myMatrix))

<class 'numpy.ndarray'>


In [2]:
class Stack:
  def __init__(self):
    self.items = []
  def isEmpty(self):
    return self.items == []
  def push(self, item):
    self.items.append(item)
  def pop(self):
    return self.items.pop()
  def peek(self):
    return self.items[len(self.items)-I]
  def size(self):
    return len(self.items)

In [4]:
stack=Stack()
stack.push('Red')
stack.push('Green')
stack.push("Blue")
stack.push("Yellow")

print(stack.pop())

print(stack.isEmpty())

Yellow
False


In [5]:
class Queue(object):
  def __init__(self):
    self.items = []
  def isEmpty(self):
    return self.items == []
  def enqueue(self, item):
    self.items.insert(0,item)
  def dequeue(self):
    return self.items.pop()
  def size(self):
    return len(self.items)

In [6]:
queue=Queue()
queue.enqueue('Red')
queue.enqueue('Green')
queue.enqueue('Blue')
queue.enqueue('Yellow')
print(queue.size())

4


In [7]:
print(queue.dequeue())
print(queue.dequeue())

Red
Green
